### ISSUE TITLE
mermaid is not work in slideshow

### ISSUE THREAD

**Issue by SepCode** [jupyterlab-contrib/rise#76]
mermaid is not work in slideshow

**Comment by djstrong** [comment]
It would be very helpful to support mermaid.

**Comment by krassowski** [comment]
Mermaid diagrams were added in https://github.com/jupyterlab/jupyterlab/pull/14102. It might be as simple as adding the new packages to https://github.com/jupyterlab-contrib/rise/blob/main/packages/application/package.json and rebuilding but I am not familiar with the codebase here so its just a guess.

**Comment by Y3drk** [comment]
@krassowski 
> Mermaid diagrams were added in [jupyterlab/jupyterlab#14102](https://github.com/jupyterlab/jupyterlab/pull/14102). It might be as simple as adding the new packages to https://github.com/jupyterlab-contrib/rise/blob/main/packages/application/package.json and rebuilding but I am not familiar with the codebase here so its just a guess.

Wanted to try that approach but encountered issues when trying to work in development mode ([another issue listed on this repo](https://github.com/jupyterlab-contrib/rise/issues/64)).

Also when I tried forking it the dependencies install failed due to some inconsistency with webpack (no idea what that was about). Anyway after the forced install the build still failed. 

The reason for that may or may not be in my setup / me using an npm instead of yarn as they do in project, but either way playing around with it is not so simple and I couldn't confirm your theory.

If you had tried it and had any luck with it I'd appreciate any info from you :)
